"""baseline

Revision ID: f48daaaa1f42
Revises: 
Create Date: 2026-07-27 19:02:24.629959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48daaaa1f42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simbad_main_id', sa.String(), nullable=True),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('ra_deg', sa.Float(), nullable=True),
    sa.Column('dec_deg', sa.Float(), nullable=True),
    sa.Column('otype', sa.String(), nullable=True),
    sa.Column('spectral_type', sa.String(), nullable=True),
    sa.Column('resolution_state', sa.String(), nullable=False),
    sa.Column('planets_lookup_failed', sa.Boolean(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidates_json', sa.Text(), nullable=True),
    sa.Column('resolved_via_json', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resolution_state IN ('RESOLVED','AMBIGUOUS','PARTIAL','UNRESOLVED','LOOKUP_FAILED')", name='ck_resolution_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simbad_main_id')
    )
    op.create_index(op.f('ix_objects_query_text'), 'objects', ['query_text'], unique=False)
    op.create_table('rate_limit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("subject_type IN ('user','session','resolve_user','resolve_session')", name='ck_rate_limit_subject_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_limit_events_subject_created', 'rate_limit_events', ['subject_type', 'subject_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gemini_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('gemini_preferred_model', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('identifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('catalog', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('matched_exoplanet_archive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'catalog', 'identifier', name='uq_identifier')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('pl_name', sa.String(), nullable=False),
    sa.Column('pl_letter', sa.String(), nullable=True),
    sa.Column('orbital_period_days', sa.Float(), nullable=True),
    sa.Column('planet_radius_earth', sa.Float(), nullable=True),
    sa.Column('discovery_year', sa.Integer(), nullable=True),
    sa.Column('discovery_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_text')
    )
    op.create_index(op.f('ix_query_aliases_object_id'), 'query_aliases', ['object_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'object_id', name='uq_saved_search')
    )
    op.create_table('user_summary_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'object_id', name='uq_user_summary_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_summary_snapshots')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_query_aliases_object_id'), table_name='query_aliases')
    op.drop_table('query_aliases')
    op.drop_table('planets')
    op.drop_table('identifiers')
    op.drop_table('users')
    op.drop_index('ix_rate_limit_events_subject_created', table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    op.drop_index(op.f('ix_objects_query_text'), table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###
